# Generated by Django 2.0.4 on 2018-06-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestialbody',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
    ]
