# Generated by Django 2.0.4 on 2018-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180612_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='name',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
