# Generated by Django 2.0.4 on 2018-06-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180612_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='average_distance',
            field=models.FloatField(default=0, help_text='Average distance from the parent body'),
        ),
    ]
