# Generated by Django 2.0.4 on 2018-06-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180612_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celestialbody',
            name='surface_pressure',
            field=models.FloatField(default=0, help_text='This is the atmospheric pressure (the weight of the atmosphere per unit area) at the surface of the planet in bars or atmospheres. *The surfaces of Jupiter, Saturn, Uranus, and Neptune are deep in the atmosphere and the location and pressures are not known.'),
        ),
    ]
