

const TWITTER_SCREEN_NAME = 'POTUS';
const TWITTER_HEIGHT = '700';
const TWITTER_USERNAME = 'President';
const TWITTER_WIDTH = '450';


export {TWITTER_SCREEN_NAME, TWITTER_WIDTH, TWITTER_HEIGHT, TWITTER_USERNAME}